# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e6f351bec148bdea5ebb6e13fdfadb00f6ba99b7ed8288b50f071be45c9c2f16128cadd83a60cf7491c7dbf52253becc9de10633b7c48641e1917ba066bbb157

test:
  secret_key_base: b97ec94629aefdd66551e2d5aeb26455f23069ee6dda0ff30dfc00efb19c3dcdd432b24c7345b138fbd49fac2aadbd5057b6b0098c3d2240419476dbd2ceef61

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
