# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 574237bdeae89c23ebaa73d9865c1184326363a456b27e4004a6300a5b97f9880ab1232cc5e3c75e67cb3a48e3ad0359c38344250299031ac0015f56061f91d6

test:
  secret_key_base: 44e927009f58d2d0ddee8042c51b179ede1bb18d820c201614c967fb8bcd892d269823ab58fc99b4e0f6c87ab4c55de6116e691164ca45600f37dd573cd034d2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
